### ISSUE TITLE
Druid.scroll freezes if held in one place for a long time

### ISSUE THREAD

**Issue by notbadgun** [Insality/druid#118]
**Describe the bug**
The "druid.scroll" freezes if held in one place for a long time, if the FRICT_HOLD is less than 0.5
The rest of the style settings are like this:

_ANIM_SPEED = 0.2, -- gui.animation speed to point
BACK_SPEED = 0.35, -- Lerp speed of return to soft position
FRICT = 0.83, -- mult for free inert
FRICT_HOLD = 0.49, -- mult. for inert, while touching
INERT_THRESHOLD = 20, -- speed to stop inertion
INERT_SPEED = 70, -- koef. of inert speed
EXTRA_STRETCH_SIZE = 20, -- extra size in pixels outside of scroll (stretch effect)
POINTS_DEADZONE = 20, -- Speed to check points of interests in no_inertion mode
SCROLL_WHEEL_SPEED = 20,
SMALL_CONTENT_SCROLL = true, -- If true, content node with size less than view node size can be scrolled_

**To Reproduce**
Set the style settings as above.

**Demo1:**
https://user-images.githubusercontent.com/13905665/106368038-bda5db00-6357-11eb-9f92-3506c35e5279.mp4

**Demo2:**
https://user-images.githubusercontent.com/13905665/106368277-81737a00-6359-11eb-979d-bc6dc0017c43.mp4

**Comment by Insality** [comment]
it should be fixed in #43, already in develop branch
