### ISSUE TITLE
Set_click_zone(zone) function for Druid.scroll

### ISSUE THREAD

**Issue by notbadgun** [Insality/druid#124]
It is necessary to add "set_click_zone(zone)" function for "druid.scroll"

Example:
![GIF](https://user-images.githubusercontent.com/13905665/112608423-596d3800-8e2b-11eb-8979-f270d7ecf174.gif)

**Comment by Insality** [comment]
@notbadgun as fast solution, you can restrict zone via `set_click_zone` in drag component of scroll:
`self.scroll.drag:set_click_zone(node)`

**Comment by Insality** [comment]
In develop added function _scroll:set_click_zone_. It links to similar _scroll.drag.set_click_zone_ function. Will be available in the next release
