### ISSUE TITLE
Missing release for v0.10.0

### ISSUE THREAD

**Issue by unindented** [Insality/druid#196]
@Insality is there a reason why there's no git tag, nor GitHub release, for v0.10.0? I can point to a specific commit in my Defold project, but using tags feels nicer.

**Comment by Insality** [comment]
Hello! Thanks for the issue :) 

The 0.10.0 release is still in development and not published yet. There are some issues in new release, so I need the time to polish it 🙃

**Comment by unindented** [comment]
Ah understood. Thank you for all your work!
