### ISSUE TITLE
Slider component doesn't support styles

### ISSUE THREAD

**Issue by unindented** [Insality/druid#197]
I'd like to tweak the color of the pin in my slider components, with things like `on_hover` and `on_mouse_hover`, just like I do with buttons. I don't think it's possible at the moment, cause `Slider` doesn't make use of styles at all.

**Comment by Insality** [comment]
Oh, hello!

i think the slider will not be supported with styles in future and more "standart" way is to after slider and a hover component with you additional style logic

It can be grouped in your own custom component to use it more easily and it can looks like this

```lua
local component = require("druid.component")

---@class my_slider: druid.base_component
local M = component.create("my_slider")


function M:init()
	self.druid = self:get_druid()

	self.slider = self.druid:new_slider("slider_node", vmath.vector3(100, 0, 0))
	self.hover = self.druid:new_hover("slider_node")
	self.hover.on_mouse_hover:subscribe(self.on_hover)
end


function M:on_hover(state)
	local alpha = state and 1.5 or 1
	gui.animate(self.slider.node, gui.PROP_SCALE, vmath.vector3(alpha), gui.EASING_OUTSINE, 0.2)
end


return M
```
