### ISSUE TITLE
Having to click twice to unselect one input field and select another?

### ISSUE THREAD

**Issue by scalemaildev** [Insality/druid#199]
Currently in order to unselect one input field and select another you have to click twice. The first click unselects input A and the second selects input B. Is there any way to combine this behavior so that it behaves more like a typical internet form?

**Comment by Insality** [comment]
Probably yea, I'll try to comfort way to do this :)

**Comment by Insality** [comment]
Currently testing the solution, pushed in develop branch, you can see the attached commit to take this changes right now if you want

It will be additional input style flag to consume input while input is selected. It's mean other input components also can be interacted while Input field is selected

It's provide behaviour like your wrote in the issue

**Comment by Insality** [comment]
Also seems it will be enabled by default, since it not very good behaviour in several other cases. It will be changed later a little
