### ISSUE TITLE
data_list:scroll_to_index(t) function was broken

### ISSUE THREAD

**Issue by notbadgun** [Insality/druid#207]
The data_list:scroll_to_index(t) function was broken in version 0.10.0
It just doesn't scroll at all.
Everything is fine in version 0.9.0  (and under).

**Comment by Insality** [comment]
Thanks for the issue report. Fixed in master, add release 0.10.1 for this

It was broken in 0.9.1, currently I reverted some changes

Sorry for inconvenience
