### ISSUE TITLE
Multitouch handling not working.

### ISSUE THREAD

**Issue by gustavocodigo** [Insality/druid#218]
Unnable to handle touchs in touchscreen devices it only recognize the first touch.

As it is a very good ui and mainly to be used in games adding multitouch support by default would be a great implementation.

**Comment by Insality** [comment]
Thanks for issue!

Currently Druid is not support the multitouch directly (it supports in Drag component for example, to be sure that drag is correct between different touches)

What is your use case? The on-screen navigation? Probably it should be done without default Druid button component. If other case - write please!

I have the issue to make an example with this type of component: https://github.com/Insality/druid/issues/141

**Comment by igugx** [comment]
I say absolutely everything, using scrolls, drags grids, if you have an option to enable it, so that all components handle touches correctly, that would be good
