### ISSUE TITLE
Disabling button animations 

### ISSUE THREAD

**Issue by jcbk101** [Insality/druid#223]
Not sure if this is intended, and I am still learning the system, but Hover and on_clicks cancel my animations when using druid.

My work around was  [code] button.anim_node = nil[/code] but then it errors from 'style.lua'...
```lua
on_click = function(self, node)
		local scale_to = self.start_scale + M.button.SCALE_CHANGE
		anims.tap_scale_animation(self, node, scale_to)  -- Error here
		settings.play_sound(M.button.BTN_SOUND)
	end
```

Maybe it can be...
```lua
	on_click = function(self, node)
		local scale_to = self.start_scale + M.button.SCALE_CHANGE
		if node then anims.tap_scale_animation(self, node, scale_to) end
		settings.play_sound(M.button.BTN_SOUND)
	end
```

**Comment by Insality** [comment]
Hello! Not sure that are you trying to do

Anim node is required for button component. It's used in button style (default/style.lua)
You can copy this style.lua file and change the animations for button. After that set your style file as default (druid.set_default_style())

**Comment by jcbk101** [comment]
Thanks. I have taken care of it. I was using the wrong component for my task.


________________________________
