### ISSUE TITLE
vertical sliders

### ISSUE THREAD

**Issue by czinczaar** [Insality/druid#229]
Hi, 
about vertical sliders: it seems the end pos can only be positive? If not, how do you make a proper vertical slider?
Thanks.

**Comment by Insality** [comment]
Hello! Scrolls are fine, they can work in any direction

You have a kind if camera (scroll_view node) and game map (scroll_content). So you can scroll through all the map

You can check the examples here https://insality.github.io/druid/druid/ and also make note how the GUI layout is created (for scroll view/content)

If you have any concrete question, please answer :)

**Comment by Temeez** [comment]
I'm fairly sure there is a bug in the sliders. I cannot drag the pin if the `end_pos` is negative.

I moved the pin to the 0 position for testing purposes.
![image](https://github.com/Insality/druid/assets/3135774/a1a9e3d1-0449-454d-943c-fed182c625ba)
### Works
This works as expected. I can use mouse to drag the pin to the right to increase the value. `--->`
```lua
local scroll_slider = self.druid:new_slider("grid_scroll_pin", vmath.vector3(287, 0, 0), function (_, value)
    grid_scroll:scroll_to_percent(vmath.vector3(value, 0, 0), true)
end)
```

### Does not work
Cannot use mouse to drag the pin. Pin _should_ be draggable to the left to increase the value `<---` but it does not move.
```lua
local scroll_slider = self.druid:new_slider("grid_scroll_pin", vmath.vector3(-287, 0, 0), function (_, value)
    grid_scroll:scroll_to_percent(vmath.vector3(value, 0, 0), true)
end)
```

This issue persist for both horizontal and vertical. I tried to make a vertical scroll but got stopped by this issue when trying to make a slider where 0 value is at the top and 1 value is at the bottom. There was a broken success by rotating the `grid_scroll_slider` `Z` by 180 degrees but then dragging motion was opposite of the pin go direction.

**Comment by Dolbaeb777K** [comment]
> Hello! Scrolls are fine, they can work in any direction
> ...
> If you have any concrete question, please answer :)

No, he meant **Sliders**
_Vertical_ **Sliders**

**No** scrolls

So, I have this issue too
I just want vertical sliders, but I don't know how to do that...

https://github.com/user-attachments/assets/63271437-7e60-4e13-bda3-331a1c254a5f

So. how you can see, it works only with horizontal dragging. But I want normal vertical dragging works.
How can I do that with druid Framework?

**Comment by Insality** [comment]
There is a bug with a sliders, it currently don'y work in negative direction as I remember (so you can try from bottom to up in this case)

Will be fixed in next release and will add several examples

**Comment by Dolbaeb777K** [comment]
> ... (so you can try from bottom to up in this case)
Sorry. What do you mean?

**Comment by Insality** [comment]
You can make it without rotation. Just place a "pin" node at bottom and use the higher position to set in the code


https://github.com/user-attachments/assets/5f6684f2-b373-45b6-b13f-2b8a3927dcae

**Comment by Dolbaeb777K** [comment]
Thanks!

https://github.com/user-attachments/assets/5cbe1925-1eae-47c0-a555-6cf97ffd320d

I am leaving a video to share with everyone.

**Comment by Dolbaeb777K** [comment]
Oh, no. Why it doesn't work 😭 ...

https://github.com/user-attachments/assets/17d40ef3-61e0-477e-a7e9-a6cb5bee21a9

It just get a nil value. Why?
```
INFO:ENGINE: Initialised sound device 'default'
DEBUG:SCRIPT: [Druid]: The component slider is extended component. You have to register it via druid.register to use it
DEBUG:SCRIPT: [Druid]: Use next code:
DEBUG:SCRIPT: local slider = require("druid.extended.slider")
DEBUG:SCRIPT: druid.register("slider", slider)
ERROR:SCRIPT: main/GUI/Slider_Up.gui_script:9: attempt to index local 'slider' (a nil value)
stack traceback:
  main/GUI/Slider_Up.gui_script:9: in function <main/GUI/Slider_Up.gui_script:4>

ERROR:GAMESYS: Error when initializing gui component: RESULT_SCRIPT_ERROR.
```
**WARNING!** I use `https://github.com/Insality/druid/archive/refs/heads/update.zip` for my project because I use the latest Defold version.

**Comment by Insality** [comment]
> DEBUG:SCRIPT: [Druid]: The component slider is extended component. You have to register it via druid.register to use it
> DEBUG:SCRIPT: [Druid]: Use next code:
> DEBUG:SCRIPT: local slider = require("druid.extended.slider")
> DEBUG:SCRIPT: druid.register("slider", slider)
```lua
local slider = require("druid.extended.slider")
druid.register("slider", slider)
```

**Comment by Dolbaeb777K** [comment]
> local slider = require("druid.extended.slider")
> druid.register("slider", slider)

Bruh. Bro, sorry... I am linux user but I forgot that I have to read errors completely )
My bad, man. Thanks a lot again! )
