### ISSUE TITLE
Input component and styles bug

### ISSUE THREAD

**Issue by InfinityZxc** [Insality/druid#239]
In Input [init](https://github.com/Insality/druid/blob/b5b07cb8d90d4cb31fe40f0220c147f2e5ab218d/druid/extended/input.lua#L144) function `self.button:set_style` is called with argument `self.button_style` but `self` doesn't have such element. There is [self.style.button_style](https://github.com/Insality/druid/blob/b5b07cb8d90d4cb31fe40f0220c147f2e5ab218d/druid/extended/input.lua#L105), but including into account how `set_style` works, `self.style` should be passed. Furthermore, table that is passed to `set_style` should have elements with the same names, as components [_based on this_](https://github.com/Insality/druid/blob/b5b07cb8d90d4cb31fe40f0220c147f2e5ab218d/druid/component.lua#L71C1-L71C1), so every variable in default style and `Input.on_style_change` with the name `button_style` should be renamed into `button`.
Finally `Input.on_style_change` doesn't pass changes to the button component, something like `self.button:set_style(self.style)` at the end with relevant checks should fix this.

UPD: default input style already has correct field called `button`, but it doesn't work without fixing `Input.on_style_change`

**Comment by Insality** [comment]
Ha-ha, only now get some time to clean the issue backlog, sorry.

Thanks for the detailed information! Got attempt to understand why is it exists and finally just remove this all section with button_style.

Since we can directly change style on each component this is not required
