### ISSUE TITLE
Bug is new update

### ISSUE THREAD

**Issue by eduardr** [Insality/druid#240]
Hi,

Just letting you know there's a bug in the latest version.
Scrolling doesn't work any more for me with the new version in iOS and Android.
But it still works fine when using the mouse in HTML5 version.

best regards.

**Comment by eduardr** [comment]
It seems to be another issue

**Comment by Insality** [comment]
Please check your input bindings
They were changed to the Defold defaults in Druid v10

https://github.com/Insality/druid/blob/master/docs_md/advanced-setup.md#input-bindings

**Comment by eduardr** [comment]
Thank you, I reverted back to v9 and that fixed the issue indeed.
