### ISSUE TITLE
Question about StaticGrid:remove()

### ISSUE THREAD

**Issue by NaakkaDev** [Insality/druid#248]
Is it expected that when using the `StaticGrid` `remove` method with a shift the actual gui nodes are moved? I was confused when I used `remove` without `gui.delete_node(deleted_node)` since it visually looks like it removes the node from gui, but after I figured out how to print the node tree it looks like it just moves the grid item on top of another one.

It would be good if the [documentation](https://insality.github.io/druid/modules/StaticGrid.html#remove) tells what the shift policy does more precisely. I had always assumed that it only shifts the items in the `nodes` array.

Btw. I like druids quite a lot, thank you for making it! :)

**Comment by Insality** [comment]
Hello! As I remember - yes, the StaticGrid can manage nodes position and it's related to add/remove nodes too.

By default it's shift nodes to the Left, like usual table.remove do, but you can specify shift policy to None to don't move them on remove function

Thanks for suggestion, try to figure out how to describe all of this better
