### ISSUE TITLE
It Scrolls In Reverse

### ISSUE THREAD

**Issue by ahmutkadim** [Insality/druid#257]
As I mentioned on the title, in the example project of Druid, main menu scrolls in reverse according to input given. I am using MacOS and a trackpad, would that be the case, what can be done?

**Comment by Insality** [comment]
Hello! The scroll have the option to inverse the mouse wheel direction. So if required you can adjust how it should be inside your game

`WHEEL_SCROLL_INVERTED bool If true, invert direction for touchpad and mouse wheel scroll (default false)`

https://insality.github.io/druid/modules/Scroll.html#style
