### ISSUE TITLE
Can't build without example/assets folder

### ISSUE THREAD

**Issue by ViK0s** [Insality/druid#261]
I cannot build my projects without copying the examples/assets directory from the repo. While trying to build for desktop it steers me to the rich_text.gui with this error:

> /druid/custom/rich_text/rich_text.gui
> 	The file '/example/assets/fonts/game.font' could not be found.
> 	The file '/example/assets/images/kenney.atlas' could not be found.

I tried to fix that by changing the default font used by it. While that fixes it for the desktop build, it makes me unable to build HTML5 with the error:

> /game.project
> 	Unable to find resource example/assets/fonts/game.fontc

I have already checked if it could be because of different libraries by running inside a new project with only druid, but the errors persist.
I use defold version 1.7.0 and druid version 0.11.0

**Comment by Insality** [comment]
Thanks for the issue!

To solve it now, you can make a copy the `rich_text.gui` to your game folder, adjust the textures/font it used and use it instead of the library template

This is more correct way to use it, honestly

**Comment by ViK0s** [comment]
Ah, makes sense 😅 

Thank you for help!
