### ISSUE TITLE
How to resize a druid scroll containing a data list ?

### ISSUE THREAD

**Issue by 0xbeefbeef** [Insality/druid#276]
I have a scroll area with a data list. it is set up like this, taken from the example project, more less
```

self.scroll_vertical = self.druid:new_scroll("data_list_vertical", "data_list_vertical_content"):set_horizontal_scroll(false)
self.grid_vertical = self.druid:new_static_grid("data_list_vertical_content", "prefab", 1)
self.data_list_vertical = self.druid:new_data_list(scroll_vertical, grid_vertical, create_vertical_element)
self.data_list_vertical.on_element_add:subscribe(on_element_add)
self.data_list_vertical.on_element_remove:subscribe(on_element_remove)
```

The data list is fed from an external server, and this works as expected. However, I have a scenario in which i want to shrink the scroll area to yield room for another item/widget. i do this with e.g.
```self.scroll_vertical:set_size(new_size, vmath.vector3(0, 0, 0))```

this doesnt work as expected. I also tried to shrink the underlying gui nodes too, an the scroll area looks fine then. however, i cannot scroll down to the last elements of the data list, as i could do before i was shrinking the scroll area. Any ideas or suggestions how to do shrink a scroll area with a nested data list properly? Thanks

**Comment by Insality** [comment]
Hello! I think a perfect way will be to me to add an example for this. But it will take a some time until complete :)

On resizing scroll in `set_size` it only changes the content node 
I think you can add this function to scroll or call it similary to update the view_size of scroll:

```lua
function Scroll.set_view_size(self, size)
	gui.set_size(self.view_node, size)
	self.view_size = size
	self.view_border = helper.get_border(self.view_node)
	self:_update_size()
end
```

Then probably the data_list should be updated somehow, but not sure

**Comment by 0xbeefbeef** [comment]
Hi Maksim, thank you very much :-) . I will try the method you suggested and let you know if that works.
