### ISSUE TITLE
Color for text on button

### ISSUE THREAD

**Issue by ufgo** [Insality/druid#277]
It wouldn't be a bad idea to add changes for the colour of not only the button itself, but also the text inside it. I don't know how to do it better. For example, by prefixing the text node. If the button is ‘btn’, then the text inside it should be ‘btn_txt’.

**Comment by Insality** [comment]
The button component not always mean you have a text component on it or other text node

So in your case it should be a function like this and use this function to change the color of your button
```lua
function M:set_color(widget, color)
    gui.set_color(self.button.node, color)
    gui.set_color(self.text.node, color)
end
```
