### ISSUE TITLE
A lot of errors while building a source (from github repo) project...

### ISSUE THREAD

**Issue by Dolbaeb777K** [Insality/druid#279]
I just want to understand how works one or the other code and make some changes for this.
But I have a lot of errors while building the game project.
Look,
 
![Screenshot_20241014_130424](https://github.com/user-attachments/assets/a29696fb-f352-4f2f-bbdf-881b30431ed2)

What I need to install or to do for it work?

Also, I use Linux (Astra Linux).

**Comment by Dolbaeb777K** [comment]
Also I tried to  build HTML5. Look at log:
[log.txt](https://github.com/user-attachments/files/17360650/log.txt)

**Comment by Insality** [comment]
This is an error from update of Defold extension for ~1.9.2+

You can try is fix works in the branch update:
https://github.com/Insality/druid/tree/update

**Comment by Dolbaeb777K** [comment]
> This is an error from update of Defold extension for ~1.9.2+
> 
> You can try is fix works in the branch update: https://github.com/Insality/druid/tree/update

Thanks! It works! But I tired in windows, I will try it on openSUSE Tumbleweed soon...
![image](https://github.com/user-attachments/assets/bed3396e-4916-492d-a64f-9ab3ecff61b0)

**Comment by Dolbaeb777K** [comment]
> This is an error from update of Defold extension for ~1.9.2+
> 
> You can try is fix works in the branch update: https://github.com/Insality/druid/tree/update

![image](https://github.com/user-attachments/assets/a6002b1d-a99e-47c1-b623-c045ca620926)
So, there it works pretty good too... )
