### ISSUE TITLE
404 Page not found... Error when fetching library with druid Update 

### ISSUE THREAD

**Issue by Dolbaeb777K** [Insality/druid#281]
![Снимок экрана_20241016_214359](https://github.com/user-attachments/assets/f940f1c7-88b2-4775-afee-a99bc88c9fec)
![image](https://github.com/user-attachments/assets/07c70552-6f66-4721-b0c5-3b21d974fbe7)
Errors, when trying fetching library with druid `Update` and trying to download from github page.

**Comment by Insality** [comment]
Hello

This is not actual release, it's a link from branch that was created to prepare release

You should use `https://github.com/Insality/druid/archive/refs/tags/0.11.0.zip` or if you want go experimental use `https://github.com/Insality/druid/archive/refs/heads/update.zip` until the release is prepared

But this "update" branch can be removed any time
