### ISSUE TITLE
Drag component have wrong x coordinate on resized window

### ISSUE THREAD

**Issue by boruok** [Insality/druid#284]
found bug with drag offset calculation of drag-component along x-axis if you resize window. However i can't reproduce it if node abjust-size is set to stretch mode.

scene hierarchy
```
- go
-- gui
--- box
```

script used
```lua
local druid = require("druid.druid")

function init(self)
	self.druid = druid.new(self)
	local node = gui.get_node("box")
	self.drag = self.druid:new_drag(node, function(_, dx, dy) 
		local position_x = gui.get(self.drag.node, "position.x")
		local position_y = gui.get(self.drag.node, "position.y")
		gui.set(self.drag.node, "position.x", position_x + dx)
		gui.set(self.drag.node, "position.y", position_y + dy)
	end)
end

function final(self)
	self.druid:final()
end

function update(self, dt)
	self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
	self.druid:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
	return self.druid:on_input(action_id, action)
end
```

mrp: [My Project.zip](https://github.com/user-attachments/files/17543931/My.Project.zip)

**Comment by Insality** [comment]
Hello!
Please check you have the `window_callback` for Druid: https://github.com/Insality/druid/blob/master/docs_md/advanced-setup.md#code-bindings

```lua
-- Call this function inside window.set_listener
-- to capture game focus lost/gained callbacks:
-- window.set_listener(function(self, event, data) druid.on_window_callback(event, data) end))
local function on_window_callback(self, event, data)
    druid.on_window_callback(event)
end
window.set_listener(on_window_callback)
```

usually the reason is absent of this callback

**Comment by boruok** [comment]
my bad, binding did the trick.

**Comment by boruok** [comment]
found another issue with same mrp, coordinates are odd when gui layout changes. Should i open new issue?

**Comment by Insality** [comment]
I have not so much practice with layouts + druid cases so the best thing here is to open the another issue with minimal repro

Thanks! Will take a look, it can be something Druid related
