### ISSUE TITLE
Error when creating new button with animation node

### ISSUE THREAD

**Issue by 8bitskull** [Insality/druid#61]
I get an error on this line when I try to create a new button with an animation node:
https://github.com/Insality/druid/blob/develop/druid/base/button.lua#L168

I think it's because of the change below, when get_node was moved from helper:
https://github.com/Insality/druid/commit/080035c301274b8686cda3d370488c3ab54debfa#diff-be286c70c65555e56c461b7009e857e7

**Comment by Insality** [comment]
Oh, you are right!
Thanks for this! I will add button with _anim_node_ to main example for sure it works

**Comment by Insality** [comment]
Publish fix in 0.4.1

A lot of waiting for 0.5.0 :)
