### ISSUE TITLE
Hover events

### ISSUE THREAD

**Issue by GreenArrow18** [Insality/druid#65]
When a button is disabled via set_enabled (false), I think the hover/mouse_hover events should be disabled as well? Right now, the button still get interactions even if it's disabled.

I can probably change this via styles, but it's better if this is "fixed" in the extension itself. Thanks.

**Comment by Insality** [comment]
Yea, sorry for this, I'll take a look and fix, thanks!

_button:set_enabled_ is not fully ready yet, can you explain your use-case of it usage? Is it comfortable to enable/disable button logic?

**Comment by GreenArrow18** [comment]
Use case: I have a button that animates a game board. During the brief animation, I prefer to have the button disabled but still visible (possibly just change the button's color/alpha to indicate it's inactive). While it's disabled, it should not be responding to clicks/hovers.

If I want to hide the button itself, I can just call _gui.set_enabled_. I can see how others might be confused though (I read from the forum), if they expect button:set_enabled to show/hide the button like Defold does, so probably better to change the function name to _set_active_ or something else?

btw, if I need to add new button properties (e.g. save the original button color), can this be done via style only, or do I need to make a new component that extends button? Still trying to familiarize myself with everything...

**Comment by Insality** [comment]
Thanks for feedback!

Yea, nice suggestion about naming. Probably, I can deprecate _set_enabled_ and change to _set_active_ in this fix.

If you need additional property - styles it's nice way to do this. For example, I use it for sprite changing on button actions.

I don't planned to extend basic components, in Druid prefer composition over inheritance, if possible. But anyway, you can copy button component, change it for your needs and override it via _druid.register_. It's more Druid way I think.

**Comment by Insality** [comment]
I'll added hover:set_enabled, and disabled button also will not provide hover event anymore

I was thinking about this and finally agree, what disabled button should not react on hover events. But we still can describe disabled button interaction with styles

Fix will be in the next release, cause it's not major bug
