### ISSUE TITLE
New components

### ISSUE THREAD

**Issue by GreenArrow18** [Insality/druid#67]
`local M = component.create("my_component")`
The code above creates a brand new my_component. What if I just want to extend the existing functionality of an existing druid component e.g. a button. How can I do this?

Currently, I am using something like this:
```
function M.init(self, ...)
	self.druid = self:get_druid()
	self.button =  self.druid:new_button(...)
end
```
but then I have to override all functions like:
```
function M.set_enabled(self,state)
	self.button:set_enabled(state)
end
```

Is this the proper way to do things? Or is there a simpler way?

Thanks.

**Comment by Insality** [comment]
Right now extending components is not designed, but can be done with a little trick.

I will think more about this ability, should be it in Druid or not. Druid prefer composition and customizing components via styles should be enough. If you want replace all buttons, current way is copy _button_ component, rework it and register at druid via `druid.register()`. Register can override basic components too.

For now, you can create subclass from druid component in next-way:
```lua
local class = require("druid.system.middleclass")
local button = require("druid.base.button")

local M = class("button_custom", button)

--- Class constructor
function M.initialize(self)
	--- Call parent constructor
	button.initialize(self)
end

function M.is_enabled(self)
	print("Overridden function")
	return not self.disabled
end

return M
```

Thanks for feedback! Issue will be closed after solution for this.

**Comment by GreenArrow18** [comment]
I was trying to do it using styles only, but I can't quite figure out how to add some properties to it (for example, save the original node's color so I can manipulate it later).

I wanted to avoid copy/paste of the original button codes, because it pretty much contains the basic functionality already, so for easier code maintenance, I just like to extend it.

Your solution above actually works perfectly for my use case! I set the properties in this new extended component, then use those properties in my new style, without having to mess around further with the original button codes.

Thanks again!
