### ISSUE TITLE
Button click question

### ISSUE THREAD

**Issue by GreenArrow18** [Insality/druid#68]
Steps to reproduce:
1. Press a button (but don't release it)
2. Move the mouse outside the button
3. Move back the mouse inside the button
4. Release while inside the button

I was expecting that this will still generate a valid click event because the initial press and final release are on the same button.

However, it does not register a click event. Is this expected?

EDIT: I have modified the question and issue description, as the click outside events I previously mentioned were normal (for other buttons in the same gui).

**Comment by Insality** [comment]
In Druid, button for click event button should be pressed and released on this without leave node zone. I will add this to documentation. Thanks!

But, yea, this is the bug, _click_outside_ event should be not trigger in this case.

**Edit:** oh, see. You say it work as expected for _click_outside_. But anyway I'll check it!
