### ISSUE TITLE
Incorrect scroll mouse offset with "Adjust Mode: Zoom" on root scroll node

### ISSUE THREAD

**Issue by BlackMATov** [Insality/druid#73]
![Jun-10-2020 04-18-13](https://user-images.githubusercontent.com/2990282/84200784-77062680-aad1-11ea-9262-4960a7430194.gif)

**Comment by Insality** [comment]
Thank for report!

Now there is some problems to check real distance while using zoom/stretch without modify render_script

I'll investigate this how druid can solve this in more user-friendly way

**Comment by Insality** [comment]
Will be fixed in 0.10.0 release
