### ISSUE TITLE
Ability to delete/unregister druid nodes

### ISSUE THREAD

**Issue by 8bitskull** [Insality/druid#83]
Use case: When I select different characters in my game, I create GUI nodes to display all the skills they have. If I register them as druid buttons, I could display information about the skills as a tooltip. When I switch the characters and delete the associated nodes, I get an error.

**Comment by Insality** [comment]
Hello!
_druid:remove_ should work well. Which type of error you get?

Druid will no delete gui nodes, you will do it by yourself, but druid components can be deleted with _druid:remove_

**Comment by 8bitskull** [comment]
Thanks for the response! Sorry, I didn't find druid:remove in the documentation so I didn't realise it existed. Just testing it now and I am getting errors anyway.

I wrote this test:

```
        local test = gui.new_box_node(vmath.vector3(100,100,0), vmath.vector3(100,100,0))
	gui.set_id(test, "test")
	self.druid:new_button("test", function()print("press!") end)

	timer.delay(2,false,function()
		self.druid:remove("test")
	end)
```

I get this error:
```

ERROR:SCRIPT: /druid/system/druid_instance.lua:211: attempt to call method 'get_interests' (a nil value)
stack traceback:
	/druid/system/druid_instance.lua:211: in function 'remove'
```

The "test" button does work as expected before druid:remove is called. I also tested it with a button that was manually created in the GUI file (not using gui.new_box_node) and I get the same error.

Am I making a mistake?

**Comment by Insality** [comment]
Yea, I found the lack of documentation about druid:remove. It's pointed only in API list. I will add more info about this functions. Thanks!

You should remove the button instance, which returned from _:new_button_
Like this:
```lua
local button = self.druid:new_button("test")
self.druid:remove(button)
```

**Comment by 8bitskull** [comment]
> You should remove the button instance, which returned from :new_button

Thank you - I confirm that this works as expected.
